from pathlib import Path


PROJ_ROOT = Path(__file__).resolve().parents[1]

DATA_DIR = PROJ_ROOT / "data"
IMAGES_DIR = DATA_DIR / "images"
BRACKETED_IMAGES_DIR = IMAGES_DIR / "Bracketed_images"
LDR_DIR = IMAGES_DIR / "LDR"
HDR_DIR = IMAGES_DIR / "HDR"

NN_RESULTS_DIR = PROJ_ROOT / "nn_results_images"
OVEREXPOSED_IMAGES_DIR = NN_RESULTS_DIR / "over"
UNDEREXPOSED_IMAGES_DIR = NN_RESULTS_DIR / "under"

HDR_RECONSTRUCTION_DIR = PROJ_ROOT / "hdr_reconstruction_output"
HDR_RECONSTRUCTION_IMAGES_DIR = HDR_RECONSTRUCTION_DIR / "images"
HDR_RECONSTRUCTION_PREVIEW_DIR = HDR_RECONSTRUCTION_DIR / "preview"
HDR_TARGET_PREVIEW_DIR = HDR_RECONSTRUCTION_DIR / "target_preview"